steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  args: 
  - '-c'
  - |
    set -x && \
    gcloud compute ssh --zone "us-east1-b" "kevin-instance1"  --project "dndbot-362000" --command='/bin/sh /home/peter_l_sakr/pull.sh'
options:
  logging: CLOUD_LOGGING_ONLY